# Generated by Django 5.1.6 on 2025-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
