# Generated by Django 5.1.6 on 2025-03-23 03:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0003_messages_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
