# Generated by Django 5.1.6 on 2025-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0004_chatrooms_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatrooms',
            name='num_unread_mssgs',
            field=models.IntegerField(default=0),
        ),
    ]
