# Generated by Django 5.1.6 on 2025-04-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0006_alter_messages_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='name',
        ),
    ]
