# Generated by Django 5.1.6 on 2025-04-22 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0007_remove_chatrooms_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='chatroom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
