# Generated by Django 5.1.6 on 2025-04-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0008_alter_chatrooms_chatroom_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatrooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mssg_app.chatrooms')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('users', 'chatrooms'), name='unique_user_chatroom')],
            },
        ),
    ]
