# Generated by Django 5.1.6 on 2025-04-22 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0009_chatroommembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='users',
        ),
        migrations.AlterField(
            model_name='chatrooms',
            name='chatroom_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.DeleteModel(
            name='ChatRoomMembership',
        ),
    ]
