# Generated by Django 5.1.6 on 2025-04-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0010_remove_chatrooms_users_alter_chatrooms_chatroom_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mssg_app.chatrooms')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatrooms',
            name='users',
            field=models.ManyToManyField(through='mssg_app.ChatRoomMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatroommembership',
            constraint=models.UniqueConstraint(fields=('users', 'chatroom'), name='unique_membership'),
        ),
    ]
