# Generated by Django 5.1.6 on 2025-04-22 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0011_chatroommembership_chatrooms_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrooms',
            name='users',
            field=models.ManyToManyField(related_name='chatrooms', through='mssg_app.ChatRoomMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
