# Generated by Django 5.1.6 on 2025-04-30 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0012_alter_chatrooms_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatroom', to='mssg_app.chatrooms'),
        ),
    ]
