# Generated by Django 5.1.6 on 2025-04-30 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0013_alter_messages_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mssg_app.chatrooms'),
        ),
    ]
