# Generated by Django 5.1.6 on 2025-05-03 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0014_alter_messages_chatroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mssg_app.messages')),
            ],
        ),
    ]
