# Generated by Django 5.1.6 on 2025-05-06 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0015_messageimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageimages',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mssg_app.messages'),
        ),
    ]
