# Generated by Django 5.1.6 on 2025-05-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mssg_app', '0017_alter_messages_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatrooms',
            name='num_unread_mssgs',
        ),
        migrations.AddField(
            model_name='chatrooms',
            name='has_unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
